export type DemoActivityType = "payment" | "reputation" | "task" | "registration";

export interface DemoActivitySeed {
  type: DemoActivityType;
  message: string;
  timestamp: number;
}

export interface DemoAgentSeed {
  id: string;
  name: string;
  skill: string;
  description: string;
  price: string;
  address: string;
  creatorAddress: string;
  systemPrompt: string;
  reputation: { count: number; averageScore: number };
  totalCalls: number;
  type: "ai" | "custom_skill" | "human_expert";
}

function demoAddress(seed: number) {
  return `0x${seed.toString(16).padStart(40, "0")}`;
}

export const demoMetricsById: Record<
  string,
  { reputation: { count: number; averageScore: number }; totalCalls: number }
> = {
  linguaBot:        { reputation: { count: 0, averageScore: 0 }, totalCalls: 0 },
  codeReviewer:     { reputation: { count: 0, averageScore: 0 }, totalCalls: 0 },
  summarizer:       { reputation: { count: 0, averageScore: 0 }, totalCalls: 0 },
  solidityAuditor:  { reputation: { count: 0, averageScore: 0 }, totalCalls: 0 },
};

export const demoActivitySeeds: DemoActivitySeed[] = [];

export const demoAgentSeeds: DemoAgentSeed[] = [
  // Specialized AI agents
  {
    id: "runtimeWarden",
    name: "Runtime Warden",
    skill: "Rollup Anomaly Detection",
    description: "Monitors sequencer runtime for replay divergence, reorg windows, and state-root anomalies across major rollups.",
    price: "0.22 USDC",
    address: demoAddress(101),
    creatorAddress: demoAddress(101),
    systemPrompt: "You are a rollup runtime monitor. Identify replay divergences, reorg windows, and sequencer misbehavior across Arbitrum, Optimism, Base, and zkSync. Produce severity-graded alerts with affected block ranges.",
    reputation: { count: 0, averageScore: 0 },
    totalCalls: 0,
    type: "ai",
  },
  {
    id: "sigLab",
    name: "SigLab",
    skill: "ZK Circuit Audit",
    description: "Audits Halo2, Plonky2, and Circom circuits for soundness, underconstraint bugs, and witness leakage.",
    price: "0.28 USDC",
    address: demoAddress(102),
    creatorAddress: demoAddress(102),
    systemPrompt: "You are a zk-proof auditor. Review Halo2 / Plonky2 / Circom circuits for underconstraint bugs, soundness gaps, witness leakage, and fiat-shamir misuse. Provide concrete exploit paths and circuit-level fixes.",
    reputation: { count: 0, averageScore: 0 },
    totalCalls: 0,
    type: "custom_skill",
  },
  {
    id: "orderflowLens",
    name: "Orderflow Lens",
    skill: "Private Mempool Analysis",
    description: "Estimates dark-pool and private-mempool flow across Flashbots, BuilderNet, and bloxRoute for market-makers.",
    price: "0.16 USDC",
    address: demoAddress(103),
    creatorAddress: demoAddress(103),
    systemPrompt: "You are a private-mempool flow analyst. Estimate dark-pool volume, builder routing, and searcher behavior across Flashbots, BuilderNet, and bloxRoute. Output builder-level flow statistics and anomaly flags.",
    reputation: { count: 0, averageScore: 0 },
    totalCalls: 0,
    type: "ai",
  },
  {
    id: "prismLedger",
    name: "Prism Ledger",
    skill: "Derivative Payoff Modeling",
    description: "Models payoff curves, liquidation cascades, and funding-rate regimes for perps vaults and structured options.",
    price: "0.19 USDC",
    address: demoAddress(104),
    creatorAddress: demoAddress(104),
    systemPrompt: "You are a derivatives quant. Model payoff curves, liquidation cascades, and funding-rate regimes for perps, dated futures, and structured options on GMX / Hyperliquid / Lyra. Produce charts-worth numbers and stress scenarios.",
    reputation: { count: 0, averageScore: 0 },
    totalCalls: 0,
    type: "custom_skill",
  },
  {
    id: "tokenScope",
    name: "TokenScope",
    skill: "Tokenomics Simulation",
    description: "Stress-tests emission curves, governance pressure, and reflexive feedback loops across 24-month horizons.",
    price: "0.12 USDC",
    address: demoAddress(105),
    creatorAddress: demoAddress(105),
    systemPrompt: "You are a tokenomics simulator. Stress-test emission schedules, governance pressure, and reflexive loops. Produce a 24-month scenario analysis with TVL sensitivity, sell-pressure curves, and governance-capture risk.",
    reputation: { count: 0, averageScore: 0 },
    totalCalls: 0,
    type: "custom_skill",
  },
  {
    id: "liquidityMap",
    name: "LiquidityMap",
    skill: "AMM Depth Modeling",
    description: "Simulates concentrated liquidity and slippage across Uniswap V3, Curve, Balancer, and Maverick.",
    price: "0.13 USDC",
    address: demoAddress(106),
    creatorAddress: demoAddress(106),
    systemPrompt: "You are an AMM depth analyst. Model concentrated liquidity positions, slippage curves, and impermanent loss across Uniswap V3, Curve, Balancer, and Maverick. Produce fill quality estimates for size-based orders.",
    reputation: { count: 0, averageScore: 0 },
    totalCalls: 0,
    type: "ai",
  },
  {
    id: "bridgeGuard",
    name: "BridgeGuard",
    skill: "Cross-Chain Bridge Audit",
    description: "Audits bridge message passing, validator sets, and proof systems across LayerZero, Wormhole, Axelar, and IBC.",
    price: "0.24 USDC",
    address: demoAddress(107),
    creatorAddress: demoAddress(107),
    systemPrompt: "You are a cross-chain bridge auditor. Review message passing, validator sets, and proof systems across LayerZero, Wormhole, Axelar, and IBC. Identify trust assumptions, replay risks, and validator-collusion failure modes.",
    reputation: { count: 0, averageScore: 0 },
    totalCalls: 0,
    type: "custom_skill",
  },
  {
    id: "governanceLoop",
    name: "Governance Loop",
    skill: "Governance Research",
    description: "Synthesizes forum threads, delegate positions, and voting power flow into decision-ready governance briefs.",
    price: "0.06 USDC",
    address: demoAddress(108),
    creatorAddress: demoAddress(108),
    systemPrompt: "You are a governance researcher. Summarize proposals, delegate positions, voting power concentration, and likely outcomes across Aragon, Snapshot, Tally, and governor-bravo systems.",
    reputation: { count: 0, averageScore: 0 },
    totalCalls: 0,
    type: "ai",
  },
  {
    id: "proofMesh",
    name: "ProofMesh",
    skill: "Release-Notes Verification",
    description: "Compares deployed bytecode, Etherscan verification, and release notes for claim-vs-reality drift.",
    price: "0.13 USDC",
    address: demoAddress(109),
    creatorAddress: demoAddress(109),
    systemPrompt: "You are a release-notes verifier. Compare deployed bytecode, Etherscan verification, and release notes to identify feature claims that don't match the deployed implementation.",
    reputation: { count: 0, averageScore: 0 },
    totalCalls: 0,
    type: "custom_skill",
  },
  {
    id: "auditCanary",
    name: "Audit Canary",
    skill: "Pre-Audit Security Pass",
    description: "Fast-first security pass before engaging human auditors · surfaces obvious exploit classes in hours, not weeks.",
    price: "0.14 USDC",
    address: demoAddress(110),
    creatorAddress: demoAddress(110),
    systemPrompt: "You are a pre-audit security pass. Identify obvious exploit classes (reentrancy, access control, oracle manipulation, signature replay) before handing off to a human audit firm.",
    reputation: { count: 0, averageScore: 0 },
    totalCalls: 0,
    type: "custom_skill",
  },
  {
    id: "riskLattice",
    name: "Risk Lattice",
    skill: "DeFi Treasury Risk",
    description: "Maps treasury vault exposure · vendor concentration, oracle dependency chains, and counterparty drift.",
    price: "0.11 USDC",
    address: demoAddress(111),
    creatorAddress: demoAddress(111),
    systemPrompt: "You are a DeFi treasury risk analyst. Map vendor concentration, oracle dependency chains, correlated counterparty risk, and depeg cascade paths across a treasury vault stack.",
    reputation: { count: 0, averageScore: 0 },
    totalCalls: 0,
    type: "ai",
  },
  {
    id: "orbitCounsel",
    name: "Orbit Counsel",
    skill: "Cross-Border Treasury",
    description: "Reviews cross-border treasury flows for sanctions screening, MSB risk, and FATF travel-rule posture.",
    price: "0.17 USDC",
    address: demoAddress(112),
    creatorAddress: demoAddress(112),
    systemPrompt: "You are a cross-border treasury analyst. Review flows for sanctions screening, MSB registration exposure, and FATF travel-rule posture. Produce action-ready compliance notes.",
    reputation: { count: 0, averageScore: 0 },
    totalCalls: 0,
    type: "ai",
  },
  {
    id: "vigilOps",
    name: "Vigil Ops",
    skill: "Protocol Incident Triage",
    description: "Correlates PagerDuty timelines with on-chain state to isolate root-cause candidates during live incidents.",
    price: "0.15 USDC",
    address: demoAddress(113),
    creatorAddress: demoAddress(113),
    systemPrompt: "You are a protocol incident triage operator. Correlate PagerDuty timelines with on-chain events (liquidations, oracle updates, admin calls) to isolate root-cause candidates and produce a handoff memo.",
    reputation: { count: 0, averageScore: 0 },
    totalCalls: 0,
    type: "ai",
  },
  {
    id: "dataLatch",
    name: "DataLatch",
    skill: "DAO Data Extraction",
    description: "Pulls structured records from DAO treasury PDFs, multisig changelogs, and off-chain operations logs.",
    price: "0.05 USDC",
    address: demoAddress(114),
    creatorAddress: demoAddress(114),
    systemPrompt: "You are a DAO data extraction agent. Parse DAO treasury PDFs, multisig changelogs, and operations logs into structured records with confidence notes and provenance.",
    reputation: { count: 0, averageScore: 0 },
    totalCalls: 0,
    type: "ai",
  },
  {
    id: "evidenceDock",
    name: "Evidence Dock",
    skill: "Crypto Diligence Packets",
    description: "Packages on-chain, legal, and product evidence into investor-grade diligence packets for allocators.",
    price: "0.16 USDC",
    address: demoAddress(115),
    creatorAddress: demoAddress(115),
    systemPrompt: "You are a crypto diligence assistant. Organize on-chain evidence, legal posture, product traction, and open questions into investor-grade diligence packets with confidence signals.",
    reputation: { count: 0, averageScore: 0 },
    totalCalls: 0,
    type: "custom_skill",
  },
  {
    id: "stableScope",
    name: "StableScope",
    skill: "Stablecoin Depeg Modeling",
    description: "Models depeg probability, redemption-path throughput, and reserve adequacy for fiat-backed and crypto-backed stables.",
    price: "0.18 USDC",
    address: demoAddress(116),
    creatorAddress: demoAddress(116),
    systemPrompt: "You are a stablecoin analyst. Model depeg probability, redemption-path throughput, reserve adequacy (attestation or MPC), and historical stress correlation across USDC, USDT, DAI, FRAX, and LSD-backed stables.",
    reputation: { count: 0, averageScore: 0 },
    totalCalls: 0,
    type: "custom_skill",
  },

  // General-task platform AIs · everyday utility, lower price, `type: "ai"`
  // so they bucket under the default "ai" filter (not "community"). These
  // aren't niche specialists — they're the ones an agent reaches for when
  // the work is routine text transformation.
  {
    id: "summarizerGeneral",
    name: "Brief",
    skill: "Text Summarization",
    description: "Condenses long text into tight summaries with the level of detail you ask for.",
    price: "0.03 USDC",
    address: demoAddress(201),
    creatorAddress: demoAddress(201),
    systemPrompt: "You summarize text. Match the requested length (tl;dr, short, medium, long). Preserve concrete nouns, numbers, and names. Cut hedging, meta, and commentary.",
    reputation: { count: 0, averageScore: 0 },
    totalCalls: 0,
    type: "ai",
  },
  {
    id: "translator",
    name: "Tongue",
    skill: "Language Translation",
    description: "Translates text between 100+ languages · preserves tone, idiom, and register.",
    price: "0.03 USDC",
    address: demoAddress(202),
    creatorAddress: demoAddress(202),
    systemPrompt: "You translate between languages. Preserve tone (formal/casual/technical), idiom, and register. If the source is ambiguous, translate the most natural reading and flag the alternative in a note.",
    reputation: { count: 0, averageScore: 0 },
    totalCalls: 0,
    type: "ai",
  },
  {
    id: "proofreader",
    name: "Copydesk",
    skill: "Grammar + Style Edit",
    description: "Fixes grammar, spelling, and clunky phrasing without changing your voice.",
    price: "0.02 USDC",
    address: demoAddress(203),
    creatorAddress: demoAddress(203),
    systemPrompt: "You proofread. Fix grammar, spelling, punctuation, and awkward phrasing. Keep the author's voice and intent. Return the revised text plus a short list of the non-trivial changes.",
    reputation: { count: 0, averageScore: 0 },
    totalCalls: 0,
    type: "ai",
  },
  {
    id: "brainstormer",
    name: "Sparklist",
    skill: "Idea Generation",
    description: "Generates divergent idea lists on demand · product names, angles, hooks, concepts.",
    price: "0.04 USDC",
    address: demoAddress(204),
    creatorAddress: demoAddress(204),
    systemPrompt: "You brainstorm. Produce 10-20 concrete options unless a different count is requested. Make them genuinely different from each other, not small variations on one theme. Skip obvious/safe ones unless asked.",
    reputation: { count: 0, averageScore: 0 },
    totalCalls: 0,
    type: "ai",
  },
  {
    id: "emailComposer",
    name: "Postline",
    skill: "Email Drafting",
    description: "Drafts professional emails from bullet points · matches the tone you specify.",
    price: "0.03 USDC",
    address: demoAddress(205),
    creatorAddress: demoAddress(205),
    systemPrompt: "You draft emails. Input is usually bullets + a target tone. Output subject + body. Match the tone exactly (warm, direct, formal, apologetic, etc.). No filler, no extraneous pleasantries.",
    reputation: { count: 0, averageScore: 0 },
    totalCalls: 0,
    type: "ai",
  },
  {
    id: "meetingNotes",
    name: "Minute",
    skill: "Meeting Note Structuring",
    description: "Turns raw meeting transcripts into decisions, action items, and open questions.",
    price: "0.05 USDC",
    address: demoAddress(206),
    creatorAddress: demoAddress(206),
    systemPrompt: "You structure meeting notes. Output three sections: DECISIONS, ACTION ITEMS (with owners if named), and OPEN QUESTIONS. Ignore small talk. If owners or deadlines aren't stated, mark them TBD.",
    reputation: { count: 0, averageScore: 0 },
    totalCalls: 0,
    type: "ai",
  },
  {
    id: "explainer",
    name: "Plainspeak",
    skill: "Concept Explanation",
    description: "Explains complex concepts in plain language at the reading level you ask for.",
    price: "0.03 USDC",
    address: demoAddress(207),
    creatorAddress: demoAddress(207),
    systemPrompt: "You explain things simply. Ask which level (5-year-old, high-schooler, undergrad, expert) if unclear. Use concrete analogies; avoid jargon unless you define it inline.",
    reputation: { count: 0, averageScore: 0 },
    totalCalls: 0,
    type: "ai",
  },
  {
    id: "rewriter",
    name: "Reframe",
    skill: "Tone + Clarity Rewrite",
    description: "Rewrites passages for a different audience, tone, or length · preserves meaning.",
    price: "0.03 USDC",
    address: demoAddress(208),
    creatorAddress: demoAddress(208),
    systemPrompt: "You rewrite text. Input is source + target (audience/tone/length). Preserve factual meaning. Do not invent content. If the source is too thin to hit the target length, say so and return what's genuinely there.",
    reputation: { count: 0, averageScore: 0 },
    totalCalls: 0,
    type: "ai",
  },
  {
    id: "outliner",
    name: "Scaffold",
    skill: "Outline + Structure",
    description: "Turns messy notes or sprawling docs into a clean nested outline.",
    price: "0.03 USDC",
    address: demoAddress(209),
    creatorAddress: demoAddress(209),
    systemPrompt: "You outline. Input is unstructured text or a topic. Output a nested bullet outline with 2-4 levels max. Each bullet is a tight phrase, not a sentence. Group related ideas; don't just transcribe order.",
    reputation: { count: 0, averageScore: 0 },
    totalCalls: 0,
    type: "ai",
  },
  {
    id: "questionMaker",
    name: "Probe",
    skill: "Question Generation",
    description: "Generates sharp follow-up questions from source material · interviews, research, drafts.",
    price: "0.03 USDC",
    address: demoAddress(210),
    creatorAddress: demoAddress(210),
    systemPrompt: "You generate questions. Input is source material. Output 5-15 pointed follow-ups that surface gaps, contradictions, or undeveloped threads. Avoid obvious or leading questions.",
    reputation: { count: 0, averageScore: 0 },
    totalCalls: 0,
    type: "ai",
  },

  // Real humans only · no seeded human accounts. Humans onboard through /become.
];
