export const SKILL_CATALOG = [
  // AI agent skills (from demoData + config seeds)
  "On-Chain Forensics",
  "Solidity Exploit Detection",
  "MEV & Orderflow Analysis",
  "Regulatory & MiCA Compliance",
  "Rollup Anomaly Detection",
  "ZK Circuit Audit",
  "Private Mempool Analysis",
  "Derivative Payoff Modeling",
  "Tokenomics Simulation",
  "AMM Depth Modeling",
  "Cross-Chain Bridge Audit",
  "Governance Research",
  "Release-Notes Verification",
  "Pre-Audit Security Pass",
  "DeFi Treasury Risk",
  "Cross-Border Treasury",
  "Protocol Incident Triage",
  "DAO Data Extraction",
  "Crypto Diligence Packets",
  "Stablecoin Depeg Modeling",
  // Human expert skills
  "Crypto Securities Law (US)",
  "Smart Contract Sign-Off",
  "Tokenomics Design",
  "OFAC / Sanctions Review",
  "Bridge Security Sign-Off",
  "Exploit Incident Response",
  "ZK Soundness Review",
  "DAO Governance Precedent",
  // General-purpose categories the marketplace is missing today
  "Translation",
  "Code Review",
  "Summarization",
  "Copyediting",
  "Research",
  "Data Labeling",
  "Design Review",
  "Legal Review",
  "Expert Judgment",
  // Crypto & on-chain (deeper coverage)
  "DEX Aggregation",
  "Oracle Design",
  "Restaking Strategy",
  "Liquid Staking Review",
  "Slashing Analysis",
  "Validator Ops",
  "Node Operator Review",
  "RPC Provider Ops",
  "L2 Proving Systems",
  "Data Availability Review",
  "Sequencer Design",
  "Intent-Based Routing",
  "Account Abstraction Review",
  "Paymaster Design",
  "ENS & Naming",
  "NFT Royalty Analysis",
  "On-Chain Gaming",
  "RWA Tokenization",
  "DePIN Architecture",
  "Bitcoin Ordinals Review",
  "Flash Loan Exploit Review",
  "Reentrancy Audit",
  "Oracle Manipulation Review",
  "Key Management Review",
  "HSM Setup",
  "Multisig Ops",
  "MPC Wallet Review",
  "Cold Storage Design",
  "Crypto Tax Optimization",
  "Cost Basis Tracking",
  // Software engineering
  "Rust Audit",
  "Go Concurrency Review",
  "TypeScript Typing",
  "React Performance Review",
  "Next.js Architecture",
  "Python ML Pipeline",
  "API Design Review",
  "GraphQL Schema Review",
  "gRPC Design",
  "WebSocket Architecture",
  "Database Migration Review",
  "SQL Query Optimization",
  "Caching Strategy",
  "Fuzzing & Property Testing",
  "Formal Verification",
  "Load Testing",
  "Penetration Testing (Web)",
  // DevOps / infra
  "Kubernetes Audit",
  "Terraform Review",
  "CI/CD Pipeline Design",
  "Observability Setup",
  "Incident Postmortem",
  "On-Call Runbook Review",
  // AI / ML
  "Prompt Engineering",
  "RAG Architecture",
  "Fine-Tuning Strategy",
  "Model Evals Design",
  "Dataset Curation",
  "Bias & Safety Review",
  // Data
  "Data Cleaning",
  "ETL Pipeline Review",
  "Data Warehouse Schema",
  "Analytics Dashboard Design",
  "A/B Test Analysis",
  // Business / strategy
  "Pitch Deck Review",
  "Financial Modeling",
  "Fundraising Strategy",
  "Grant Applications",
  "Token Launch Planning",
  "Go-to-Market Strategy",
  "Competitive Analysis",
  "User Research",
  "Survey Design",
  // Writing / content
  "Technical Writing",
  "Documentation Review",
  "RFC Drafting",
  "Whitepaper Editing",
  "Changelog Drafting",
  "Marketing Copy",
  "Brand Voice Review",
  // Image generation (Gemini-backed)
  "Image · Photorealistic",
  "Image · Cute",
  "Image · Cartoon",
  "Image · Anime",
  "Image · Pixel Art",
  "Image · 3D Render",
  "Image · Watercolor",
  "Image · Cyberpunk",
  // Creative / design
  "UI/UX Review",
  "Visual Identity Review",
  "Illustration",
  "Icon Design",
  "Motion Graphics",
  "Video Editing",
  "Podcast Editing",
  "3D Modeling",
  // Community
  "Community Management",
  "DAO Facilitation",
  "Moderator Training",
  "Dispute Resolution",
  // Localized translation
  "Translation · Chinese",
  "Translation · Spanish",
  "Translation · Arabic",
  "Translation · Japanese",
  "Translation · Korean",
  "Translation · Russian",
  "Translation · French",
  "Translation · German",
  "Translation · Portuguese",
  // Legal & compliance (deeper)
  "GDPR Review",
  "KYC/AML Process Review",
  "IP & Licensing Review",
  "Employment Contract Review",
  "Privacy Policy Drafting",
  // Misc expert judgment
  "Medical Literature Review",
  "Academic Peer Review",
  "Expert Witness Prep",
  "Accessibility Audit",
] as const;

export type CatalogSkill = (typeof SKILL_CATALOG)[number];

export const SKILL_CATALOG_SET: ReadonlySet<string> = new Set(SKILL_CATALOG);

export function isCatalogSkill(s: string): s is CatalogSkill {
  return SKILL_CATALOG_SET.has(s);
}
